# complete_integration_test.py - UPDATED WITH COVER LETTER SAVING

import asyncio
import sys
import os
import json
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

# Add src to path for imports
sys.path.append('src')

from services.resume_parser import LLMResumeParser
from graph.complete_job_agent_graph import create_complete_job_agent_graph

load_dotenv()

import json
import numpy as np
from datetime import datetime
from pathlib import Path

def convert_numpy_types(obj):
    """Convert numpy types to native Python types for JSON serialization"""
    if isinstance(obj, dict):
        return {key: convert_numpy_types(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_types(item) for item in obj]
    elif isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float64, np.float32)):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    else:
        return obj
def save_all_materials_from_result(workflow_result, output_dir="saved_applications"):
    """
    Save ALL generated materials (cover letter, resume bullets, Q&A) from workflow result
    FIXED: Handles numpy float32/float64 types for JSON serialization
    """
    
    # Create output directory
    Path(output_dir).mkdir(exist_ok=True)
    
    # Extract data
    job_data = workflow_result.get('job', {})
    materials_data = workflow_result.get('materials', {})
    
    company = job_data.get('company', 'Unknown_Company').replace(' ', '_')
    job_title = job_data.get('title', 'Unknown_Position').replace(' ', '_')
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    saved_files = {}
    
    # 1. Save Cover Letter
    cover_letter = materials_data.get('cover_letter', '')
    if cover_letter:
        cover_filename = f"cover_letter_{company}_{job_title}_{timestamp}.txt"
        cover_path = os.path.join(output_dir, cover_filename)
        
        with open(cover_path, 'w', encoding='utf-8') as f:
            f.write(f"COVER LETTER - {job_data.get('title')} at {job_data.get('company')}\n")
            f.write("=" * 60 + "\n\n")
            f.write(cover_letter)
            f.write("\n\n" + "=" * 60)
            f.write(f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            
            # FIXED: Convert score to regular float
            score = workflow_result.get('score', {}).get('overall_score', 'N/A')
            if isinstance(score, (np.floating, np.float32, np.float64)):
                score = float(score)
            f.write(f"\nFit Score: {score}%")
            f.write("\nGenerated by Job Apply-Assist Agent")
        
        saved_files['cover_letter'] = cover_path
        print(f"✅ Cover letter saved: {cover_filename}")
    
    # 2. Save Resume Bullets
    resume_bullets = materials_data.get('resume_bullets', [])
    if resume_bullets:
        bullets_filename = f"resume_bullets_{company}_{job_title}_{timestamp}.txt"
        bullets_path = os.path.join(output_dir, bullets_filename)
        
        with open(bullets_path, 'w', encoding='utf-8') as f:
            f.write(f"RESUME BULLETS - {job_data.get('title')} at {job_data.get('company')}\n")
            f.write("=" * 60 + "\n\n")
            for i, bullet in enumerate(resume_bullets, 1):
                f.write(f"• {bullet}\n")
            f.write("\n" + "=" * 60)
            f.write(f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        saved_files['resume_bullets'] = bullets_path
        print(f"✅ Resume bullets saved: {bullets_filename}")
    
    # 3. Save Q&A Answers
    qa_answers = materials_data.get('qa_answers', {})
    if qa_answers:
        qa_filename = f"qa_answers_{company}_{job_title}_{timestamp}.txt"
        qa_path = os.path.join(output_dir, qa_filename)
        
        with open(qa_path, 'w', encoding='utf-8') as f:
            f.write(f"Q&A ANSWERS - {job_data.get('title')} at {job_data.get('company')}\n")
            f.write("=" * 60 + "\n\n")
            for question, answer in qa_answers.items():
                f.write(f"Q: {question.replace('_', ' ').title()}\n")
                f.write(f"A: {answer}\n\n")
            f.write("=" * 60)
            f.write(f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        saved_files['qa_answers'] = qa_path
        print(f"✅ Q&A answers saved: {qa_filename}")
    
    # 4. Save Complete Application Package (JSON) - FIXED
    package_filename = f"application_package_{company}_{job_title}_{timestamp}.json"
    package_path = os.path.join(output_dir, package_filename)
    
    # FIXED: Convert numpy types before JSON serialization
    application_package = {
        "job_details": convert_numpy_types(job_data),
        "materials": convert_numpy_types(materials_data),
        "fit_score": convert_numpy_types(workflow_result.get('score', {})),
        "generated_at": datetime.now().isoformat(),
        "files_created": saved_files
    }
    
    try:
        with open(package_path, 'w', encoding='utf-8') as f:
            json.dump(application_package, f, indent=2, ensure_ascii=False)
        
        saved_files['complete_package'] = package_path
        print(f"✅ Complete package saved: {package_filename}")
        
    except Exception as e:
        print(f"⚠️ Could not save JSON package: {str(e)}")
        # Continue anyway - the important files are already saved
    
    return saved_files

async def test_bangalore_jobs():
    """Test specifically for Bangalore jobs"""
    
    print("🎯 BANGALORE-FOCUSED JOB SEARCH TEST")
    print("=" * 60)
    print("Searching ONLY in Bangalore, India")
    print("=" * 60)
    
    # Your inputs - BANGALORE SPECIFIC
    resume_path = r"D:\Hare_Krishna_JobAgent\sreecharan_resume_2.0_with photo.pdf"
    job_type = "Data Scientist"
    location = "Bangalore"  # Correct spelling for India
    
    print(f"📄 Resume: {os.path.basename(resume_path)}")
    print(f"💼 Job Type: {job_type}")
    print(f"📍 Location: {location}")
    
    # Check API credentials
    if not os.getenv("ADZUNA_API_KEY") or not os.getenv("ADZUNA_APP_ID"):
        print("❌ Missing Adzuna API credentials")
        return
    
    print(f"✅ Adzuna API credentials found")
    
    try:
        # STEP 1: Test different Bangalore location variants
        print(f"\n🔍 STEP 1: Testing Bangalore Location Variants...")
        
        from services.job_search_service import JobSearchService
        search_service = JobSearchService()
        
        bangalore_variants = [
            "Bangalore",
            "Bengaluru", 
            "Bangalore, India",
            "Bengaluru, India",
            "Bangalore, Karnataka",
            "Bengaluru, Karnataka"
        ]
        
        best_location = None
        max_jobs = 0
        
        for location_variant in bangalore_variants:
            print(f"   Testing: '{location_variant}'")
            
            try:
                jobs = await search_service.search_jobs(
                    keywords=job_type,
                    location=location_variant,
                    limit=10
                )
                
                job_count = len(jobs)
                print(f"   ✅ Found {job_count} jobs for '{location_variant}'")
                
                if job_count > max_jobs:
                    max_jobs = job_count
                    best_location = location_variant
                
                # Show sample job for verification
                if jobs:
                    sample_job = jobs[0]
                    print(f"      Sample: {sample_job.get('title')} at {sample_job.get('company')}")
                    print(f"      Location: {sample_job.get('location')}")
                
            except Exception as e:
                print(f"   ❌ Failed for '{location_variant}': {str(e)}")
        
        print(f"\n🎯 Best location variant: '{best_location}' with {max_jobs} jobs")
        
        if max_jobs == 0:
            print("❌ No jobs found for any Bangalore variant")
            return
        
        # STEP 2: Parse resume
        print(f"\n🤖 STEP 2: Parsing Resume...")
        parser = LLMResumeParser()
        profile = await parser.parse_resume(resume_path)
        
        print(f"✅ Profile: {profile.get('name')}")
        print(f"   Skills: {', '.join(profile.get('skills', [])[:5])}")
        print(f"   Experience: {profile.get('years_experience')} years")
        
        # STEP 3: Focused Bangalore search
        print(f"\n🔍 STEP 3: Focused Bangalore Job Search...")
        
        search_filters = {
            "keywords": [job_type],
            "locations": [best_location],  # Use best location variant
            "experience_level": "mid"
        }
        
        print(f"   Using location: '{best_location}'")
        print(f"   Keywords: {search_filters['keywords']}")
        
        # Get jobs with ranking
        bangalore_jobs = await search_service.search_jobs(
            keywords=job_type,
            location=best_location,
            limit=15
        )
        
        print(f"✅ Found {len(bangalore_jobs)} Bangalore jobs")
        
        if bangalore_jobs:
            # Rank jobs for Sreecharan specifically
            ranked_jobs = rank_jobs_for_profile(bangalore_jobs, profile)
            
            print(f"\n📊 Top 5 Bangalore Jobs for {profile.get('name')}:")
            for i, job in enumerate(ranked_jobs[:5], 1):
                relevance = job.get('relevance_score', 0)
                print(f"   {i}. {job.get('title')} at {job.get('company')}")
                print(f"      Location: {job.get('location')}")
                print(f"      Salary: {job.get('salary_range', 'Not disclosed')}")
                print(f"      Relevance: {relevance} points")
                print(f"      URL: {job.get('url')[:50]}...")
                print()
        
        # STEP 4: Run complete workflow with best location
        print(f"\n🚀 STEP 4: Running Complete Workflow...")
        
        workflow_input = {
            "profile": profile,
            "search_filters": search_filters
        }
        
        job_agent = create_complete_job_agent_graph()
        result = await job_agent.ainvoke(workflow_input)
        
        # STEP 5: Verify Bangalore job selection
        print(f"\n📊 STEP 5: BANGALORE JOB VERIFICATION")
        print("=" * 50)
        
        job = result.get('job', {})
        score = result.get('score', {})
        
        print(f"🏢 SELECTED JOB:")
        print(f"   Title: {job.get('title')}")
        print(f"   Company: {job.get('company')}")
        print(f"   Location: {job.get('location')}")
        print(f"   Source: {job.get('source')}")
        
        # Verify it's Bangalore
        job_location = job.get('location', '').lower()
        is_bangalore = any(city in job_location for city in ['bangalore', 'bengaluru'])
        
        print(f"\n🎯 BANGALORE VERIFICATION:")
        if is_bangalore:
            print(f"   ✅ SUCCESS: Job is in Bangalore!")
            print(f"   Location: {job.get('location')}")
        else:
            print(f"   ❌ FAILURE: Job is NOT in Bangalore")
            print(f"   Location: {job.get('location')}")
        
        # FIXED: Verify it's real Adzuna (check both .com and .in)
        job_source = job.get('source', '')
        job_url = job.get('url', '')
        is_real_adzuna = job_source == 'adzuna' and ('adzuna.com' in job_url or 'adzuna.in' in job_url)
        
        print(f"\n🔍 ADZUNA VERIFICATION:")
        if is_real_adzuna:
            print(f"   ✅ SUCCESS: Using real Adzuna job!")
        else:
            print(f"   ❌ FAILURE: Not using real Adzuna job")
            print(f"   Source: {job_source}")
        
        # Show fit analysis
        print(f"\n🎯 FIT ANALYSIS:")
        print(f"   Overall Score: {score.get('overall_score', 0):.1f}%")
        print(f"   Recommendation: {score.get('recommendation', 'unknown').upper()}")
        
        # NEW: Save all materials to files
        print(f"\n💾 SAVING GENERATED MATERIALS...")
        saved_files = save_all_materials_from_result(result, "saved_applications")
        
        print(f"\n📁 SAVED FILES:")
        for material_type, filepath in saved_files.items():
            print(f"   ✅ {material_type}: {os.path.basename(filepath)}")
        
        # Final summary
        print(f"\n" + "=" * 60)
        print("🏁 BANGALORE SEARCH SUMMARY")
        print("=" * 60)
        print(f"✅ Location: {'Bangalore ✅' if is_bangalore else 'Not Bangalore ❌'}")
        print(f"✅ Data Source: {'Real Adzuna ✅' if is_real_adzuna else 'Not Real ❌'}")
        print(f"✅ Job Found: {job.get('title')} at {job.get('company')}")
        print(f"✅ Fit Score: {score.get('overall_score', 0):.1f}%")
        print(f"✅ Materials Saved: {len(saved_files)} files in saved_applications/")
        
        if is_bangalore and is_real_adzuna:
            print(f"\n🎉 PERFECT: Real Bangalore job from Adzuna!")
        else:
            print(f"\n⚠️ Issues found - check location or data source")
        
        return result, saved_files
        
    except Exception as e:
        print(f"❌ Bangalore test failed: {str(e)}")
        import traceback
        traceback.print_exc()
        return None, None

def rank_jobs_for_profile(jobs, profile):
    """Rank jobs specifically for the candidate profile"""
    
    candidate_skills = [skill.lower() for skill in profile.get("skills", [])]
    candidate_experience = profile.get("years_experience", 0)
    
    # Sreecharan's specific skills
    ds_skills = ['python', 'machine learning', 'data science', 'pandas', 'pytorch', 'langchain']
    
    ranked_jobs = []
    
    for job in jobs:
        relevance_score = 0
        
        job_text = f"{job.get('title', '')} {job.get('description', '')}".lower()
        job_title = job.get('title', '').lower()
        
        # Score 1: Data Science specific skills (high weight)
        ds_matches = sum(1 for skill in ds_skills if skill in job_text)
        relevance_score += ds_matches * 20
        
        # Score 2: General skill matching
        skill_matches = sum(1 for skill in candidate_skills if skill in job_text)
        relevance_score += skill_matches * 10
        
        # Score 3: Experience level (Sreecharan has 2 years)
        if 'junior' in job_title or 'associate' in job_title or 'entry' in job_title:
            relevance_score += 25  # Good for 2 years experience
        elif 'senior' not in job_title and 'lead' not in job_title:
            relevance_score += 15  # Mid-level jobs
        
        # Score 4: Title relevance
        if 'data scientist' in job_title:
            relevance_score += 30
        elif 'data' in job_title:
            relevance_score += 20
        elif 'python' in job_title:
            relevance_score += 15
        
        # Score 5: Bangalore location bonus
        job_location = job.get('location', '').lower()
        if 'bangalore' in job_location or 'bengaluru' in job_location:
            relevance_score += 10
        
        # Score 6: Salary disclosure bonus
        if job.get('salary_range') and 'not disclosed' not in job.get('salary_range', '').lower():
            relevance_score += 5
        
        job['relevance_score'] = relevance_score
        ranked_jobs.append(job)
    
    # Sort by relevance score
    ranked_jobs.sort(key=lambda x: x.get('relevance_score', 0), reverse=True)
    
    return ranked_jobs

async def test_specific_bangalore_keywords():
    """Test different Data Science keywords for Bangalore"""
    
    print(f"\n🔍 TESTING BANGALORE DATA SCIENCE KEYWORDS")
    print("=" * 50)
    
    try:
        from services.job_search_service import JobSearchService
        search_service = JobSearchService()
        
        # Different keyword combinations
        keyword_tests = [
            "Data Scientist",
            "Data Science",
            "Python Developer",
            "Machine Learning Engineer",
            "Data Analyst", 
            "AI Engineer",
            "Python Data Scientist",
            "Junior Data Scientist",
            "Associate Data Scientist"
        ]
        
        results = {}
        
        for keywords in keyword_tests:
            print(f"   Testing: '{keywords}' in Bangalore")
            
            jobs = await search_service.search_jobs(
                keywords=keywords,
                location="Bangalore",
                limit=5
            )
            
            results[keywords] = len(jobs)
            print(f"   ✅ Found {len(jobs)} jobs")
            
            if jobs:
                best_job = jobs[0]
                print(f"      Best: {best_job.get('title')} at {best_job.get('company')}")
        
        print(f"\n📊 KEYWORD PERFORMANCE SUMMARY:")
        sorted_results = sorted(results.items(), key=lambda x: x[1], reverse=True)
        
        for keywords, count in sorted_results:
            print(f"   {keywords}: {count} jobs")
        
        best_keywords = sorted_results[0][0] if sorted_results else "Data Scientist"
        print(f"\n🎯 Best keywords for Bangalore: '{best_keywords}'")
        
        return best_keywords
        
    except Exception as e:
        print(f"❌ Keyword test failed: {str(e)}")
        return "Data Scientist"

async def main():
    """Main function"""
    
    print("🇮🇳 BANGALORE JOB SEARCH OPTIMIZATION")
    print("=" * 80)
    
    # Test 1: Find best keywords
    best_keywords = await test_specific_bangalore_keywords()
    
    # Test 2: Run complete Bangalore workflow
    result, saved_files = await test_bangalore_jobs()
    
    if saved_files:
        print(f"\n🎯 YOUR COVER LETTER IS READY!")
        print("=" * 50)
        cover_letter_file = saved_files.get('cover_letter')
        if cover_letter_file:
            print(f"📄 Cover Letter: {cover_letter_file}")
            print(f"📁 All Files: saved_applications/ folder")
            
            # Also print the cover letter content
            try:
                with open(cover_letter_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                print(f"\n📝 COVER LETTER PREVIEW:")
                print("=" * 40)
                # Show first 200 characters
                preview = content.split('\n\n')[2] if len(content.split('\n\n')) > 2 else content[:200]
                print(preview[:200] + "..." if len(preview) > 200 else preview)
                print("=" * 40)
            except Exception as e:
                print(f"   Could not preview: {e}")
    
    print(f"\n🏁 BANGALORE OPTIMIZATION COMPLETE")
    print("=" * 80)

if __name__ == "__main__":
    asyncio.run(main())
