# save_cover_letter.py - Extract and save cover letter from workflow results

import json
import os
from datetime import datetime
from pathlib import Path

def save_cover_letter_from_result(workflow_result, output_dir="generated_materials"):
    """
    Extract cover letter from LangGraph workflow result and save it
    
    Args:
        workflow_result: The result from job_agent.ainvoke()
        output_dir: Directory to save the cover letter
    
    Returns:
        str: Path to saved cover letter file
    """
    
    # Create output directory if it doesn't exist
    Path(output_dir).mkdir(exist_ok=True)
    
    # Extract job and materials data
    job_data = workflow_result.get('job', {})
    materials_data = workflow_result.get('materials', {})
    
    # Get cover letter content
    cover_letter = materials_data.get('cover_letter', '')
    
    if not cover_letter:
        print("❌ No cover letter found in workflow result")
        return None
    
    # Create filename with job details
    company = job_data.get('company', 'Unknown_Company').replace(' ', '_')
    job_title = job_data.get('title', 'Unknown_Position').replace(' ', '_')
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    filename = f"cover_letter_{company}_{job_title}_{timestamp}.txt"
    filepath = os.path.join(output_dir, filename)
    
    # Create formatted content
    content = f"""COVER LETTER
============

Job: {job_data.get('title', 'N/A')}
Company: {job_data.get('company', 'N/A')}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Fit Score: {workflow_result.get('score', {}).get('overall_score', 'N/A')}%

============

{cover_letter}

============
Generated by Job Apply-Assist Agent
"""
    
    # Save to file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Cover letter saved: {filepath}")
    print(f"📄 Length: {len(cover_letter)} characters")
    print(f"🏢 Company: {job_data.get('company', 'N/A')}")
    
    return filepath

def save_all_materials_from_result(workflow_result, output_dir="generated_materials"):
    """
    Save ALL generated materials (cover letter, resume bullets, Q&A) from workflow result
    
    Args:
        workflow_result: The result from job_agent.ainvoke()
        output_dir: Directory to save materials
    
    Returns:
        dict: Paths to all saved files
    """
    
    # Create output directory
    Path(output_dir).mkdir(exist_ok=True)
    
    # Extract data
    job_data = workflow_result.get('job', {})
    materials_data = workflow_result.get('materials', {})
    
    company = job_data.get('company', 'Unknown_Company').replace(' ', '_')
    job_title = job_data.get('title', 'Unknown_Position').replace(' ', '_')
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    saved_files = {}
    
    # 1. Save Cover Letter
    cover_letter = materials_data.get('cover_letter', '')
    if cover_letter:
        cover_filename = f"cover_letter_{company}_{job_title}_{timestamp}.txt"
        cover_path = os.path.join(output_dir, cover_filename)
        
        with open(cover_path, 'w', encoding='utf-8') as f:
            f.write(f"COVER LETTER - {job_data.get('title')} at {job_data.get('company')}\n")
            f.write("=" * 60 + "\n\n")
            f.write(cover_letter)
        
        saved_files['cover_letter'] = cover_path
        print(f"✅ Cover letter saved: {cover_filename}")
    
    # 2. Save Resume Bullets
    resume_bullets = materials_data.get('resume_bullets', [])
    if resume_bullets:
        bullets_filename = f"resume_bullets_{company}_{job_title}_{timestamp}.txt"
        bullets_path = os.path.join(output_dir, bullets_filename)
        
        with open(bullets_path, 'w', encoding='utf-8') as f:
            f.write(f"RESUME BULLETS - {job_data.get('title')} at {job_data.get('company')}\n")
            f.write("=" * 60 + "\n\n")
            for i, bullet in enumerate(resume_bullets, 1):
                f.write(f"• {bullet}\n")
        
        saved_files['resume_bullets'] = bullets_path
        print(f"✅ Resume bullets saved: {bullets_filename}")
    
    # 3. Save Q&A Answers
    qa_answers = materials_data.get('qa_answers', {})
    if qa_answers:
        qa_filename = f"qa_answers_{company}_{job_title}_{timestamp}.txt"
        qa_path = os.path.join(output_dir, qa_filename)
        
        with open(qa_path, 'w', encoding='utf-8') as f:
            f.write(f"Q&A ANSWERS - {job_data.get('title')} at {job_data.get('company')}\n")
            f.write("=" * 60 + "\n\n")
            for question, answer in qa_answers.items():
                f.write(f"Q: {question.replace('_', ' ').title()}\n")
                f.write(f"A: {answer}\n\n")
        
        saved_files['qa_answers'] = qa_path
        print(f"✅ Q&A answers saved: {qa_filename}")
    
    # 4. Save Complete Application Package (JSON)
    package_filename = f"application_package_{company}_{job_title}_{timestamp}.json"
    package_path = os.path.join(output_dir, package_filename)
    
    application_package = {
        "job_details": job_data,
        "materials": materials_data,
        "fit_score": workflow_result.get('score', {}),
        "generated_at": datetime.now().isoformat(),
        "files_created": saved_files
    }
    
    with open(package_path, 'w', encoding='utf-8') as f:
        json.dump(application_package, f, indent=2, ensure_ascii=False)
    
    saved_files['complete_package'] = package_path
    print(f"✅ Complete package saved: {package_filename}")
    
    return saved_files

# Usage example for your workflow
async def run_and_save_materials():
    """
    Example: Run complete workflow and automatically save all materials
    """
    
    # Your existing workflow code
    workflow_input = {
        "profile": {
            "name": "CHINTALAPUDI SREE CHARAN",
            "email": "sreecharan@email.com",
            "skills": ["Python", "Java", "SQL", "HTML/CSS", "Flask"],
            "years_experience": 2
        },
        "search_filters": {
            "keywords": ["Data Scientist"],
            "locations": ["Bangalore"]
        }
    }
    
    # Run the workflow
    from graph.complete_job_agent_graph import create_complete_job_agent_graph
    job_agent = create_complete_job_agent_graph()
    result = await job_agent.ainvoke(workflow_input)
    
    # Save all materials
    saved_files = save_all_materials_from_result(result)
    
    print(f"\n🎯 ALL MATERIALS SAVED:")
    for material_type, filepath in saved_files.items():
        print(f"   {material_type}: {os.path.basename(filepath)}")
    
    return saved_files

if __name__ == "__main__":
    # Test with a sample result structure
    sample_result = {
        'job': {
            'title': 'Data Scientist',
            'company': 'Veltris',
            'url': 'https://www.adzuna.in/land/ad/5322718855...'
        },
        'materials': {
            'cover_letter': 'Dear Hiring Manager,\n\nI am excited to apply for the Data Scientist position at Veltris...',
            'resume_bullets': [
                'Developed machine learning models using Python and scikit-learn',
                'Analyzed large datasets to identify business insights and trends'
            ],
            'qa_answers': {
                'why_interested': 'I am passionate about data science and machine learning',
                'salary_expectations': 'Open to discussing competitive package'
            }
        },
        'score': {'overall_score': 36.7}
    }
    
    # Test saving
    saved_files = save_all_materials_from_result(sample_result)
    print(f"Test completed - {len(saved_files)} files saved")
